"""empty message

Revision ID: 3c9b3554112e
Revises: bd0b0afb6d6a
Create Date: 2017-12-22 20:27:56.388817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c9b3554112e'
down_revision = 'bd0b0afb6d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
